import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { SESSION_COOKIE_MAX_AGE_SECONDS } from "./session-config";
import { THUMBS_DISCLOSURE } from "./strings";

// Run 10: Rare Tomato is a personal, open-source, provided-as-is project. No banner, nothing about legal review or who wrote a page, no "beta",
// "made-up", "fictional" or "United States only" wording, and nothing that claims to meet any law. These tests scan what people are shown.

const root = process.cwd();
const walk = (dir: string, re: RegExp): string[] =>
  fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) return e.name === "node_modules" || e.name === ".next" ? [] : walk(p, re);
    return re.test(e.name) && !/\.test\./.test(e.name) && !/\.d\.ts$/.test(e.name) ? [p] : [];
  });

/** Lines that are shown to people: everything in the app's screens and shared wording, minus comments. */
const shownFiles = [...walk(path.join(root, "src/app"), /\.tsx?$/), path.join(root, "src/lib/strings.ts"), path.join(root, "src/lib/agent-guides.ts"), path.join(root, "src/lib/blocked-data.ts"), path.join(root, "src/lib/handler.ts"), path.join(root, "src/lib/mcp.ts"), path.join(root, "src/lib/profile.ts")];
const shownLines = shownFiles.flatMap((f) =>
  fs.readFileSync(f, "utf8").split(/\r?\n/).map((text, i) => ({ f: path.relative(root, f), n: i + 1, text })).filter(({ text }) => !/^\s*(\/\/|\*|\/\*|\{\/\*)/.test(text)),
);
// Plain documents a person may read.
const docFiles = [path.join(root, "README.md"), ...walk(path.join(root, "docs/guides"), /\.md$/)];
const docLines = docFiles.flatMap((f) => fs.readFileSync(f, "utf8").split(/\r?\n/).map((text, i) => ({ f: path.relative(root, f), n: i + 1, text })));

const hits = (lines: { f: string; n: number; text: string }[], re: RegExp) => lines.filter((l) => re.test(l.text)).map((l) => `${l.f}:${l.n}: ${l.text.trim().slice(0, 110)}`);

const LEGAL_OR_AUTHOR = /legal review|lawyer|attorney|legal advice|not legal|professional (legal )?review|qualified professional|reviewed by|written by|prepared by|drafted by|authored by|generated by (an )?AI|AI-generated/i;
// "DRAFT" in capitals, "(draft)", or a page, notice or terms described as a draft. (A rule being drafted for you is a different thing and is allowed.)
const DRAFT_PAGE = /\s\(draft\)|\bDRAFT\b/;
const DRAFT_PAGE_CI = /\s\(draft\)|(this|these) (page|notice|terms|policy|document)s? (is|are) (a )?draft|draft (terms|privacy notice|privacy policy)|terms \(draft\)/i;
const OLD_SCOPE = /\bbeta\b|made-up|made up (data|details)|fictional|united states only|\bus only\b|only for (adults in )?the united states|intended for adults in the united states/i;
const CLAIMS_COMPLIANCE = /\b(compliant|complies with|in compliance with|GDPR|CCPA|HIPAA|COPPA|fully compliant|meets? (the )?(requirements|laws|rules))\b/i;

describe("what people are shown", () => {
  it("found the screens and the shared wording", () => {
    expect(shownFiles.length).toBeGreaterThan(20);
    expect(docFiles.length).toBeGreaterThan(3);
  });

  it("never mentions legal review, a lawyer, being a draft, 'not legal advice' or who wrote a page", () => {
    expect(hits(shownLines, LEGAL_OR_AUTHOR)).toEqual([]);
    expect(hits(shownLines, DRAFT_PAGE)).toEqual([]);
    expect(hits(shownLines, DRAFT_PAGE_CI)).toEqual([]);
    expect(hits(docLines, LEGAL_OR_AUTHOR)).toEqual([]);
    expect(hits(docLines, DRAFT_PAGE)).toEqual([]);
    expect(hits(docLines, DRAFT_PAGE_CI)).toEqual([]);
  });

  it("has no 'beta', 'made-up details only', 'fictional' or 'United States only' wording", () => {
    expect(hits(shownLines, OLD_SCOPE)).toEqual([]);
    expect(hits(docLines, OLD_SCOPE)).toEqual([]);
  });

  it("never claims to meet or comply with a law", () => {
    expect(hits(shownLines, CLAIMS_COMPLIANCE)).toEqual([]);
    expect(hits(docLines, CLAIMS_COMPLIANCE)).toEqual([]);
  });

  it("never describes an agent, a rule or a score as verified, enforced or guaranteed, except to say we have NOT verified something", () => {
    const risky = /\b(verified|enforced|enforces|enforcement|guaranteed|guarantees)\b/i;
    const allowedNegative = /\b(not|never|no|nothing|cannot|can't|without|have not|has not)\b[^.]{0,80}\b(verified|enforced|enforces|enforcement|guaranteed|guarantee)|\b(guarantee)\b[^.]{0,30}\bnot\b|prompt, not a guarantee|advice, not enforcement/i;
    const wording = shownLines.filter((l) => !["src/lib/handler.ts", "src/lib/mcp.ts", "src/lib/profile.ts"].includes(l.f.split(path.sep).join("/")));
    const bad = wording.filter((l) => risky.test(l.text) && !allowedNegative.test(l.text)).map((l) => `${l.f}:${l.n}: ${l.text.trim().slice(0, 110)}`);
    expect(bad).toEqual([]);
  });
});

describe("the thumbs-down sheet", () => {
  it("tells the person what is sent to Anthropic, right under the note field", () => {
    expect(THUMBS_DISCLOSURE).toBe("This sends the task summary, your feedback and your rules in this category to Anthropic to draft a rule.");
    const form = fs.readFileSync("src/app/feed/FeedbackForm.tsx", "utf8");
    expect(form.indexOf("<textarea")).toBeGreaterThan(-1);
    expect(form.indexOf("{THUMBS_DISCLOSURE}")).toBeGreaterThan(form.indexOf("<textarea"));
    expect(form.indexOf("{THUMBS_DISCLOSURE}")).toBeLessThan(form.indexOf("H.send"));
  });
});

describe("the sign-in session", () => {
  it("lasts 30 days, not the library's 400-day default", async () => {
    expect(SESSION_COOKIE_MAX_AGE_SECONDS).toBe(2_592_000);
    expect(fs.readFileSync("src/instrumentation.ts", "utf8")).toContain("WORKOS_COOKIE_MAX_AGE");
    expect(fs.readFileSync(".env.example", "utf8")).toMatch(/^WORKOS_COOKIE_MAX_AGE=\s*$/m);
    // the library reads this setting itself: check it really turns it into the cookie's Max-Age
    const original = process.env.WORKOS_COOKIE_MAX_AGE;
    process.env.WORKOS_COOKIE_MAX_AGE = String(SESSION_COOKIE_MAX_AGE_SECONDS);
    try {
      const { vi } = await import("vitest");
      vi.resetModules();
      const modulePath = "../../node_modules/@workos-inc/authkit-nextjs/dist/esm/cookie.js";
      const cookie = (await import(/* @vite-ignore */ modulePath)) as { getCookieOptions: (url: string, asString: boolean) => string };
      expect(cookie.getCookieOptions("https://agent-care.vercel.app/", true)).toMatch(/Max-Age=2592000/);
    } finally {
      if (original === undefined) delete process.env.WORKOS_COOKIE_MAX_AGE;
      else process.env.WORKOS_COOKIE_MAX_AGE = original;
    }
  });
});
